version: 2
updates:
  # Daily security updates only
  - package-ecosystem: gomod
    directory: /
    target-branch: security-updates
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    # Only allow security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"

  # Weekly regular updates (weekends) - Minor and Patch updates
  - package-ecosystem: gomod
    directory: /
    target-branch: minor-patch-updates
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    # Group minor and patch updates together
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Explicitly ignore security and major updates
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # Weekly regular updates (weekends) - Major updates only
  - package-ecosystem: gomod
    directory: /
    target-branch: major-updates
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    # Group major updates separately
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
    # Explicitly ignore security, minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"