version: 2
updates:
  # Daily security updates only
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    security-updates-only: true

  # Weekly regular updates (weekends) - Minor and Patch updates
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    # Group minor and patch updates together
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Exclude security updates and major updates
    ignore:
      - dependency-name: "*"
        update-types: ["security-update", "version-update:semver-major"]

  # Weekly regular updates (weekends) - Major updates only
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    # Group major updates separately
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    # Exclude security updates, minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: ["security-update", "version-update:semver-minor", "version-update:semver-patch"]